config/routes.rb
Rails.application.routes.draw do
  get 'about_us/index'

  resources :products
  get 'welcome/index'

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :product_images, dependent: :destroy
	accepts_nested_attributes_for :product_images
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
	belongs_to :product

	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.product_images.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(
        :name, :price, :description,
         product_images_attributes: [:product_id, :id, :photo, :caption, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about_us/index.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 pright1px">
		<div class="white-background">
			<h1 class="logo-font ptop10px">About Us</h1>
			<p class="logo-font">We Buy & Sell New & Used Construction Equipment! Trade-Ins also Accepted!</p>

			<h2 class="logo-font">What We Offer</h2>
			<p class="logo-font">Brands Such As, But not Limited to:</p>
			<span class="logo-font">Attachments Asv Bobcat Bad Boy Badger Case Caterpillar DeWalt Ditch Witch Gator Gehl Genie Graco Hitachi Husqvarna Hyster Ingersoll Rand JCB JLG JRB John Deere Komatsu Kubota Liebherr Massey Miller Multiquip Ferguson New Holland Stihl Skyjack Skytrak Takeuchi Toro Dingo Vermeer Wacker Yale Yanmar Yamaha Backhoe Boom Lift Bulldozer Excavator Mini Backhoe Mini Excavator Bobcat MT Dingo Skidsteer Skid Steer Loader Skid Loader Wheel Loader </span>
		</div>
	</div>
	<div class="col-md-1"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StEquipment</title>
  <link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="background">
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "ST Equipment", welcome_index_path, class: "navbar-brand logo-font" %></a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><%= link_to "Current Inventory", products_path %><span class="sr-only">(current)</span></a></li>
	        <li><%= link_to "About Us", about_us_index_path %></a></li>
	      </ul>
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div id="container">
		<%= yield %>
	</div>
	
</body>
<div class="panel-footer navbar-fixed-bottom">

</html>

app/views/products/_form.html.erb
<%= form_for @product, html: {multipart: true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :product_images do |builder| %>
    <% if builder.object.new_record? %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :price %><br>
        <%= f.number_field :price %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= builder.label :caption, "Image Caption" %>
        <%= builder.text_field :caption %>
      </div>  
      <div class="field">
        <%= builder.label :photo, "Image File" %>
        <%= builder.file_field :photo %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  <% end %>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-3">
      <%= image_tag product.product_images.first.photo.url :medium %>
    </div>
    <div class="col-md-4">
      <p><%= product.product_images.first.caption %></p>
      <h1><%= product.name %></h1>
      <p>Price:<%= product.price %></p>
      <p><%= product.description %></p>
    </div>
  <% end %>
</div>
<div class="row">
  <hr>
</div>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("image1.jpg", alt: "logo") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("image2.jpg", alt: "logo") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("image3.jpg", alt: "logo") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("image4.jpg", alt: "logo") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>